/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class base_ShortPointer */

#ifndef _Included_base_ShortPointer
#define _Included_base_ShortPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     base_ShortPointer
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_base_ShortPointer__1dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_ShortPointer
 * Method:    _get
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_base_ShortPointer__1get
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_ShortPointer
 * Method:    _next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_base_ShortPointer__1next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_ShortPointer
 * Method:    _set
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_base_ShortPointer__1set
  (JNIEnv *, jobject, jlong, jshort);

#ifdef __cplusplus
}
#endif
#endif
