/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alwaysthere_FloatPointer */

#ifndef _Included_base_FloatPointer
#define _Included_base_FloatPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alwaysthere_FloatPointer
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_base_FloatPointer__1dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     alwaysthere_FloatPointer
 * Method:    _get
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_base_FloatPointer__1get
  (JNIEnv *, jobject, jlong);

/*
 * Class:     alwaysthere_FloatPointer
 * Method:    _set
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_base_FloatPointer__1set
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     alwaysthere_FloatPointer
 * Method:    _next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_base_FloatPointer__1next
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
