/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_VectorIterator*/

#ifndef _Included_org_ogre4j_VectorIterator_
#define _Included_org_ogre4j_VectorIterator_
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:		org_ogre4j_VectorIterator
 * Method:		VectorIterator
 * Signature:	(VV)V;
 */
JNIEXPORT void JNICALL Java_org_ogre4j_VectorIterator_createInstance(JNIEnv *, jclass, jlong, jlong);

/*
 * Class:		org_ogre4j_VectorIterator
 * Method:		hasMoreElements
 * Signature:	(J)Z;
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_VectorIterator_hasMoreElements(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_VectorIterator
 * Method:		getNext
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_VectorIterator_getNext(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_VectorIterator
 * Method:		peekNext
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_VectorIterator_peekNext(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_VectorIterator
 * Method:		peekNextPtr
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_VectorIterator_peekNextPtr(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_VectorIterator
 * Method:		moveNext
 * Signature:	(J)V;
 */
JNIEXPORT void JNICALL Java_org_ogre4j_VectorIterator_moveNext(JNIEnv *, jclass, jlong);

/*
 * Class:     org_ogre4j_VectorIterator
 * Method:    dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_VectorIterator_dispose (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif