/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_ConstVectorIterator*/

#ifndef _Included_org_ogre4j_ConstVectorIterator_
#define _Included_org_ogre4j_ConstVectorIterator_
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:		org_ogre4j_ConstVectorIterator
 * Method:		ConstVectorIterator
 * Signature:	(VV)V;
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ConstVectorIterator_createInstance(JNIEnv *, jclass, jlong, jlong);

/*
 * Class:		org_ogre4j_ConstVectorIterator
 * Method:		hasMoreElements
 * Signature:	(J)Z;
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_ConstVectorIterator_hasMoreElements(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_ConstVectorIterator
 * Method:		getNext
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_ConstVectorIterator_getNext(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_ConstVectorIterator
 * Method:		peekNext
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_ConstVectorIterator_peekNext(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_ConstVectorIterator
 * Method:		peekNextPtr
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_ConstVectorIterator_peekNextPtr(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_ConstVectorIterator
 * Method:		moveNext
 * Signature:	(J)V;
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ConstVectorIterator_moveNext(JNIEnv *, jclass, jlong);

/*
 * Class:     org_ogre4j_ConstVectorIterator
 * Method:    dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ConstVectorIterator_dispose (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif