/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class base_LongPointer */

#ifndef _Included_base_LongPointer
#define _Included_base_LongPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     base_LongPointer
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_base_LongPointer__1dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_LongPointer
 * Method:    _get
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_base_LongPointer__1get
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_LongPointer
 * Method:    _next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_base_LongPointer__1next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_LongPointer
 * Method:    _set
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_base_LongPointer__1set
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
