/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class base_CharPointer */

#ifndef _Included_base_CharPointer
#define _Included_base_CharPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     base_CharPointer
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_base_CharPointer__1dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_CharPointer
 * Method:    _get
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_base_CharPointer__1get
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_CharPointer
 * Method:    _next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_base_CharPointer__1next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_CharPointer
 * Method:    _set
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_base_CharPointer__1set
  (JNIEnv *, jobject, jlong, jchar);

#ifdef __cplusplus
}
#endif
#endif
