/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_ConstMapIterator*/

#ifndef _Included_org_ogre4j_ConstMapIterator_
#define _Included_org_ogre4j_ConstMapIterator_
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:		org_ogre4j_ConstMapIterator
 * Method:		ConstMapIterator
 * Signature:	()V;
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ConstMapIterator_createInstance(JNIEnv *, jclass, j, j);

/*
 * Class:		org_ogre4j_ConstMapIterator
 * Method:		hasMoreElements
 * Signature:	(J)Z;
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_ConstMapIterator_hasMoreElements(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_ConstMapIterator
 * Method:		getNext
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_ConstMapIterator_getNext(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_ConstMapIterator
 * Method:		peekNextValue
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_ConstMapIterator_peekNextValue(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_ConstMapIterator
 * Method:		peekNextKey
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_ConstMapIterator_peekNextKey(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_ConstMapIterator
 * Method:		peekNextValuePtr
 * Signature:	(J);
 */
JNIEXPORT j JNICALL Java_org_ogre4j_ConstMapIterator_peekNextValuePtr(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_ConstMapIterator
 * Method:		moveNext
 * Signature:	(J)V;
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ConstMapIterator_moveNext(JNIEnv *, jclass, jlong);

/*
 * Class:     org_ogre4j_ConstMapIterator
 * Method:    dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ConstMapIterator_dispose (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif