/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class base_IntegerPointer */

#ifndef _Included_base_IntegerPointer
#define _Included_base_IntegerPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     base_IntegerPointer
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_base_IntegerPointer__1dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_IntegerPointer
 * Method:    _get
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_base_IntegerPointer__1get
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_IntegerPointer
 * Method:    _next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_base_IntegerPointer__1next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_IntegerPointer
 * Method:    _set
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_base_IntegerPointer__1set
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
