/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class base_DoublePointer */

#ifndef _Included_base_DoublePointer
#define _Included_base_DoublePointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     base_DoublePointer
 * Method:    _dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_base_DoublePointer__1dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_DoublePointer
 * Method:    _get
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_base_DoublePointer__1get
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_DoublePointer
 * Method:    _next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_base_DoublePointer__1next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     base_DoublePointer
 * Method:    _set
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_base_DoublePointer__1set
  (JNIEnv *, jobject, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
