/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_MapIterator*/

#ifndef _Included_org_ogre4j_MapIterator_
#define _Included_org_ogre4j_MapIterator_
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:		org_ogre4j_MapIterator
 * Method:		MapIterator
 * Signature:	(VV)V;
 */
JNIEXPORT void JNICALL Java_org_ogre4j_MapIterator_createInstance(JNIEnv *, jclass, jlong, jlong);

/*
 * Class:		org_ogre4j_MapIterator
 * Method:		hasMoreElements
 * Signature:	(J)Z;
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_MapIterator_hasMoreElements(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_MapIterator
 * Method:		getNext
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_MapIterator_getNext(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_MapIterator
 * Method:		peekNextValue
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_MapIterator_peekNextValue(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_MapIterator
 * Method:		peekNextKey
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_MapIterator_peekNextKey(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_MapIterator
 * Method:		peekNextValuePtr
 * Signature:	(J)V;
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_MapIterator_peekNextValuePtr(JNIEnv *, jclass, jlong);

/*
 * Class:		org_ogre4j_MapIterator
 * Method:		moveNext
 * Signature:	(J)V;
 */
JNIEXPORT void JNICALL Java_org_ogre4j_MapIterator_moveNext(JNIEnv *, jclass, jlong);

/*
 * Class:     org_ogre4j_MapIterator
 * Method:    dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_MapIterator_dispose (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif